[[mousetrap_windows]]
arch = "x86_64"
git-tree-sha1 = "c26ccd29dbe97e6f5a0466ef4e29cfcf6d06241e"
os = "windows"

    [[mousetrap_windows.download]]
    sha256 = "0ac2caf78f669f76f88bf9d6ec14176ce65adf12d01db1df47aa28de475d096e"
    url = "https://github.com/Clemapfel/mousetrap_windows_jll/releases/download/mousetrap_windows-v0.1.0+0/mousetrap_windows.v0.1.0.x86_64-w64-mingw32.tar.gz"
