[[mousetrap_windows]]
arch = "x86_64"
git-tree-sha1 = "3439c4a779b0708de9276a6b8c2df55d61f7f70f"
os = "windows"

    [[mousetrap_windows.download]]
    sha256 = "e9fbe7613b20fabe6f4da48884eea890acae23bf3fbd634ffc087158e3588bfa"
    url = "https://github.com/Clemapfel/mousetrap_windows_jll/releases/download/mousetrap_windows-v0.1.0+0/mousetrap_windows.v0.1.0.x86_64-w64-mingw32.tar.gz"
