[[mousetrap_windows]]
arch = "x86_64"
git-tree-sha1 = "f0ba2a29d9aebfd9ef259b945182aff604b9fa91"
os = "windows"

    [[mousetrap_windows.download]]
    sha256 = "03d11564854ad111759379a6f43020b58e9188e4e5c57bbf1b1eba54dfce2e9c"
    url = "https://github.com/Clemapfel/mousetrap_windows_jll/releases/download/mousetrap_windows-v0.2.0+0/mousetrap_windows.v0.2.0.x86_64-w64-mingw32.tar.gz"
