[[mousetrap_windows]]
arch = "x86_64"
git-tree-sha1 = "e9f27ed64d5cc2e07fca096452d1c5a4f67652a2"
os = "windows"

    [[mousetrap_windows.download]]
    sha256 = "57f6999f81f73cc7ec5ae9134f3a21edb40b4ed8e0a339c0fd0dc1cf313334dd"
    url = "https://github.com/Clemapfel/mousetrap_windows_jll/releases/download/mousetrap_windows-v0.2.0+0/mousetrap_windows.v0.2.0.x86_64-w64-mingw32.tar.gz"
