# Autogenerated wrapper script for mousetrap_windows_jll for x86_64-w64-mingw32
export mousetrap_julia_binding_windows, mousetrap_windows

using GLEW_jll
using GTK4_jll
using OpenGLMathematics_jll
using libcxxwrap_julia_jll
using libjulia_jll
using X11_jll
JLLWrappers.@generate_wrapper_header("mousetrap_windows")
JLLWrappers.@declare_library_product(mousetrap_julia_binding_windows, "libmousetrap_julia_binding.dll")
JLLWrappers.@declare_library_product(mousetrap_windows, "libmousetrap.dll")
function __init__()
    JLLWrappers.@generate_init_header(GLEW_jll, GTK4_jll, OpenGLMathematics_jll, libcxxwrap_julia_jll, libjulia_jll, X11_jll)
    JLLWrappers.@init_library_product(
        mousetrap_julia_binding_windows,
        "bin\\libmousetrap_julia_binding.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        mousetrap_windows,
        "bin\\libmousetrap.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
